INSERT INTO topping (id, description, image_url, name, unit_price) VALUES (1, 'This is Anchovies', '', 'Anchovies', 2);
INSERT INTO topping (id, description, image_url, name, unit_price) VALUES (2, 'This is Spring Onion', '', 'Spring Onion', 0.5);
INSERT INTO topping (id, description, image_url, name, unit_price) VALUES (3, 'This is Indian Butter Sauce', '', 'Indian Butter Sauce', 1);
INSERT INTO topping (id, description, image_url, name, unit_price) VALUES (4, 'This is Capsicum', '', 'Capsicum', 1.5);
INSERT INTO topping (id, description, image_url, name, unit_price) VALUES (5, 'This is Seasoned Chicken', '', 'Seasoned Chicken', 3);

INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (1, 'Huge Pie cut into 8 extra-large slices. Authentic soft and foldable New York Style dough topped with garlic sauce, cherry tomatoes, creamy mozzarella and oregano', '', 'THE BIG MARGHERITA', 'small', 17.95);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (2, 'Huge Pie cut into 8 extra-large slices. Authentic soft and foldable New York Style dough topped with garlic sauce, cherry tomatoes, creamy mozzarella and oregano', '', 'THE BIG MARGHERITA', 'big', 24.95);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (3, 'Huge pie cut into 8 extra-large slices topped with tender Philly Steak, mushrooms, red onion and capsicum on a tasty American style cheddar sauce base.', '', 'THE BIG PHILLY CHEESE STEAK', 'small', 27.85);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (4, 'Huge pie cut into 8 extra-large slices topped with tender Philly Steak, mushrooms, red onion and capsicum on a tasty American style cheddar sauce base.', '', 'THE BIG PHILLY CHEESE STEAK', 'big', 32.85);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (5, 'Huge pie cut into 8 extra-large slices. Authentic soft and foldable New York style dough topped with mozzarella', '', 'THE BIG CHEESE', 'small', 17.95);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (6, 'Huge pie cut into 8 extra-large slices. Authentic soft and foldable New York style dough topped with mozzarella', '', 'THE BIG CHEESE', 'big', 23.95);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (7, 'Succulent chicken with jalapenos, mushrooms, red onion, capsicum, fresh tomato on a tomato base topped with a spiced Indian butter sauce swirl & spring onion', '', 'BUTTER CHICKEN	', 'small', 19.95);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (8, 'Succulent chicken with jalapenos, mushrooms, red onion, capsicum, fresh tomato on a tomato base topped with a spiced Indian butter sauce swirl & spring onion', '', 'BUTTER CHICKEN	', 'big', 26.95);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (9, 'Ground beef, crispy rasher bacon, mushroom, pepperoni, Italian sausage, fresh baby spinach, smoked leg ham, pineapple, topped with oregano, tomato capsicum sauce & spring onion.', '', 'LOADED SUPREME	', 'small', 26.85);
INSERT INTO pizza_type (id, description, image_url, name, size, unit_price) VALUES (10, 'Ground beef, crispy rasher bacon, mushroom, pepperoni, Italian sausage, fresh baby spinach, smoked leg ham, pineapple, topped with oregano, tomato capsicum sauce & spring onion.', '', 'LOADED SUPREME	', 'big', 32.85);

